In [1]:
# pip install numpy

In [4]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.ones((2,2), dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [13]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [21]:
np.arange(3,5)

array([3, 4])

In [ ]:
#. 0, 1 , 2 , 3 , 4
#. ]3,5]

In [28]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [32]:
np.array([(1,2,3),(4,5,6)]).shape

(2, 3)

In [31]:
np.array([1,2,3,4]).shape

(4,)

In [34]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
np.arange(20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [43]:
np.ones_like(np.arange(6).reshape(3,2))

array([[1, 1],
       [1, 1],
       [1, 1]])

In [46]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
np.arange(1000000).reshape(10000,100)

array([[     0,      1,      2, ...,     97,     98,     99],
       [   100,    101,    102, ...,    197,    198,    199],
       [   200,    201,    202, ...,    297,    298,    299],
       ...,
       [999700, 999701, 999702, ..., 999797, 999798, 999799],
       [999800, 999801, 999802, ..., 999897, 999898, 999899],
       [999900, 999901, 999902, ..., 999997, 999998, 999999]])

In [51]:
# Suma
a = np.array([10,10,10])
b = np.array([5,5,5])
a + b

array([15, 15, 15])

In [52]:
# Resta
a - b

array([5, 5, 5])

In [55]:
# Multiplicacion
a * b

array([50, 50, 50])

In [56]:
# Division
a / b

array([2., 2., 2.])

In [57]:
a

array([10, 10, 10])

In [58]:
# Mod
a % 2

array([0, 0, 0])

In [63]:
# Expresiones
a = np.array([10,5,12])

In [66]:
a < 11

array([ True,  True, False])

In [67]:
A = np.array([[0,1],[2,3]])
B = np.array([[4,5],[6,7]])

In [72]:
print(A)
print(B)
# print(A * B)
# A.dot(B)
np.dot(A,B)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ 6,  7],
       [26, 31]])

In [73]:
a

array([10,  5, 12])

In [74]:
a *= 3

In [75]:
a

array([30, 15, 36])

In [76]:
arreglo_numeros = np.arange(1,11)

In [77]:
arreglo_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arreglo_numeros.sum()

55

In [79]:
arreglo_numeros.min()

1

In [80]:
arreglo_numeros.max()

10

In [81]:
numeros = np.arange(12).reshape(3,4)

In [82]:
numeros

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
numeros.sum(axis=0) # Columnas

array([12, 15, 18, 21])

In [85]:
numeros.sum(axis=1) # Filas

array([ 6, 22, 38])

In [86]:
angulos = np.array([0,30,45,60,90])

In [87]:
angulos

array([ 0, 30, 45, 60, 90])

In [88]:
angulos_en_radianes = angulos * (np.pi/180)

In [89]:
angulos_en_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [90]:
np.radians(angulos)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [91]:
np.degrees(angulos_en_radianes)

array([ 0., 30., 45., 60., 90.])

In [93]:
# Seno
np.sin(angulos)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [94]:
# Seno
np.sin(angulos_en_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [95]:
# Coseno
np.cos(angulos_en_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [97]:
# Tangente
np.tan(angulos_en_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [98]:
notas = np.array([1,2,4,3,2,1,2,4,5,6,7,8,9,8,7,6,5,4,3,2,1,2,4,6,9])

In [100]:
notas.mean()

4.44

In [102]:
np.median(notas)

4.0

In [103]:
np.std(notas)

2.515233587561998

In [104]:
np.var(notas)

6.3264

In [105]:
salarios = np.genfromtxt("./salarios.csv", delimiter=",")

In [106]:
salarios

array([1., 2., 3., 4., 5., 6., 7., 8., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
       5., 3., 2., 1., 2., 3., 4., 5., 6.])

In [107]:
salarios.mean()

4.3076923076923075

In [108]:
arreglo_once = np.arange(11)**2

In [109]:
arreglo_once

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [117]:
print(arreglo_once[0:5])
print(arreglo_once[-10:-2])
print(arreglo_once[:8])
print(arreglo_once[5:])
print(arreglo_once[2:8:4])
print(arreglo_once[::-2])
print(arreglo_once[::2])

[ 0  1  4  9 16]
[ 1  4  9 16 25 36 49 64]
[ 0  1  4  9 16 25 36 49]
[ 25  36  49  64  81 100]
[ 4 36]
[100  64  36  16   4   0]
[  0   4  16  36  64 100]


In [118]:
estudiantes = np.array([
    ['Adrian','Vicente','Wendy','Carolina'],
    [1,2,3,4],
    [5,6,7,8]
])

In [119]:
for i in estudiantes:
    print(f"Valor: {i}")

Valor: ['Adrian' 'Vicente' 'Wendy' 'Carolina']
Valor: ['1' '2' '3' '4']
Valor: ['5' '6' '7' '8']


In [124]:
for i in estudiantes.flatten(order='F'):
    print(f"Valor individual: {i}")

Valor individual: Adrian
Valor individual: 1
Valor individual: 5
Valor individual: Vicente
Valor individual: 2
Valor individual: 6
Valor individual: Wendy
Valor individual: 3
Valor individual: 7
Valor individual: Carolina
Valor individual: 4
Valor individual: 8


In [126]:
estudiantes.flatten().reshape(3,4)

array([['Adrian', 'Vicente', 'Wendy', 'Carolina'],
       ['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U8')

In [127]:
# nditer
arreglo_tres_cuatro = np.arange(12).reshape(3,4)

In [128]:
arreglo_tres_cuatro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
for i in np.nditer(arreglo_tres_cuatro, 
                   order="F",
                   flags=["external_loop"]):
    print(f"Valor: {i}")

Valor: [0 4 8]
Valor: [1 5 9]
Valor: [ 2  6 10]
Valor: [ 3  7 11]


In [140]:
arreglo_split = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [144]:
print(np.split(arreglo_split,6))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]


In [151]:
print(np.split(arreglo_split,[9,12]))

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12]), array([], dtype=int64)]


In [154]:
a = np.arange(11)

In [160]:
a.sort(axis=-1)

In [161]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
randomico = np.random.randint(1,3, size=10)

In [183]:
randomico

array([2, 1, 2, 2, 1, 2, 2, 1, 1, 1])